
stages:
  - build
  - test

before_script:
  - echo 'drop database if exists irida_test; create database irida_test' | mysql -u test -ptest
  - pushd lib
  - ./install-libs.sh
  - popd

service_job:
#running service layer tests
  script:
  - mvn clean verify -Pservice_testing
  stage: test
ui_job:
#running ui tests
  script:
  - xvfb-run mvn clean verify -Pui_testing
  stage: test
rest_job:
#running rest api tests
  script:
  - mvn clean verify -Prest_testing
  stage: test
galaxy_job:
#lastly, run all tests involving Galaxy
  script:
  - "scripts/galaxy-docker.sh"
  stage: test
build-docs_job:
  script: "scripts/build-docs.sh"
  stage: build
cache:
  untracked: true
  paths:
    - src/main/webapp/node
    - src/main/webapp/node_modules
    - src/main/webapp/resources/bower_components