services:
  - mariadb:10.0
  - apetkau/galaxy-irida-16.10-it:0.1

stages:
  - test
  #- build

variables:
  MYSQL_DATABASE: irida_test
  MYSQL_ROOT_PASSWORD: test
  MYSQL_USER: test
  MYSQL_PASSWORD: test
  JDBC_URL: jdbc:mysql://mariadb:3306/irida_test


before_script:
  - pushd lib
  - ./install-libs.sh
  - popd
  - rm -r /tmp/irida/*

#service_job:
#running service layer tests
#  tags:
#  - docker
#  image: docker.corefacility.ca:5000/irida-testing:latest
#  script:
#  - mvn clean verify -Pservice_testing -Djdbc.url=$JDBC_URL
#  stage: test
#ui_job:
#running ui tests
#  tags:
#  - docker
#  image: docker.corefacility.ca:5000/irida-testing:latest
#  script:
#  - xvfb-run --auto-servernum --server-num=1 mvn clean verify -Pui_testing -Dwebdriver.chrome.driver=./src/main/webapp/node_modules/chromedriver/lib/chromedriver/chromedriver -Djdbc.url=$JDBC_URL -Dirida.it.nosandbox=true 
#  stage: test
#rest_job:
#running rest api tests
#  tags:
#  - docker
#  image: docker.corefacility.ca:5000/irida-testing:latest
#  script:
#  - mvn clean verify -Prest_testing -Djdbc.url=$JDBC_URL
#  stage: test
galaxy_job:
##lastly, run all tests involving Galaxy
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  script:
  - mvn clean verify -B -Pgalaxy_testing -Djdbc.url=$JDBC_URL
  stage: test
#build-docs_job:
#  tags:
#  - docker
#  image: maven:3.5.0-jdk-8
#  script: "scripts/build-docs.sh"
#  stage: build
cache:
  untracked: true
  paths:
    - src/main/webapp/node
    - src/main/webapp/node_modules
    - src/main/webapp/resources/bower_components
