services:
  - mariadb:10.0

stages:
  - test
#  - build

variables:
  MYSQL_DATABASE: irida_test
  MYSQL_USER: test
  MYSQL_PASSWORD: test


before_script:
  - ci/init.sh

service_job:
#running service layer tests
  tags:
  - docker
  image: maven:3.5.0-jdk-8
  script:
  - mvn clean verify -Pservice_testing -Djdbc.url=jdbc:mysql://mariadb:3306/irida_test
  stage: test
#ui_job:
##running ui tests
#  script:
#  - xvfb-run --auto-servernum --server-num=1 mvn clean verify -Pui_testing -Dwebdriver.chrome.driver=./src/main/webapp/node_modules/chromedriver/lib/chromedriver/chromedriver
#  stage: test
#rest_job:
##running rest api tests
#  script:
#  - mvn clean verify -Prest_testing
#  stage: test
#galaxy_job:
##lastly, run all tests involving Galaxy
#  script:
#  - "scripts/galaxy-docker.sh"
#  stage: test
#build-docs_job:
#  script: "scripts/build-docs.sh"
#  stage: build
cache:
  untracked: true
  paths:
    - src/main/webapp/node
    - src/main/webapp/node_modules
    - src/main/webapp/resources/bower_components
