
stages:
  - build
  - test
  - deploy


service_job:
#running service layer tests
  script: "scripts/integration-tests-service.sh"
  stage: test
ui_job:
#running ui tests
  script: "scripts/integration-tests-ui.sh"
  stage: test
rest_job:
#running rest api tests
  script: "scripts/integration-tests-rest.sh"
  stage: test
galaxy_job:
#lastly, run all tests involving Galaxy
  script: "scripts/integration-tests-galaxy.sh"
  stage: test
build-docs_job:
  script: "scripts/build-docs.sh"
  stage: build