job1:
#running service layer tests
  script: "scripts/integration-tests-service.sh"
job2:
#running ui tests
  script: "scripts/integration-tests-ui.sh"
job3:
#running rest api tests
  script: "scripts/integration-tests-rest.sh"
job4:
  script: "scripts/build-docs.sh"