
stages:
  - build
  - test

before_script:
# remove Galaxy directories and drop/create databases before tests start
  - rm -rf /tmp/gxbootstrap*
  - rm -rf /tmp/shed_tools/
  - pkill -u gitlab-runner -f "python ./scripts/paster.py" || true
  - echo 'drop database if exists irida_test; drop database if exists irida_galaxy_test; create database irida_test;create database irida_galaxy_test;' | mysql -u test -ptest
  - pushd lib
  - ./install-libs.sh
  - popd

service_job:
#running service layer tests
  script: "scripts/integration-tests-service.sh"
  stage: test
ui_job:
#running ui tests
  script: "scripts/integration-tests-ui.sh"
  stage: test
rest_job:
#running rest api tests
  script: "scripts/integration-tests-rest.sh"
  stage: test
galaxy_job:
#lastly, run all tests involving Galaxy
  script: "scripts/integration-tests-galaxy.sh"
  stage: test
build-docs_job:
  script: "scripts/build-docs.sh"
  stage: build