sudo: required
language: java

services:
  - docker
  - mysql

jdk:
  - openjdk8

cache:
    directories:
      - $HOME/.m2

install:
  - mysql -e 'CREATE USER "test"@"localhost" IDENTIFIED BY "test"; GRANT ALL ON irida_integration_test.* to "test"@"localhost";'
  - mvn -version
  - pushd lib; ./install-libs.sh; popd
  - docker pull phacnml/galaxy-irida-17.01

script: ./run-tests.sh galaxy_testing
