sudo: required
language: java

env:
  global:
    - MYSQL_DATABASE=irida_integration_test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test

services:
  - docker
  - mysql

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

stages:
  - doc
  - test

install:
  - mysql -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'localhost';"
  - mvn -version
  - pushd lib; ./install-libs.sh; popd

jobs:
  include:
    - stage: doc
      script: mvn clean site -B
    - stage: test
      script: ./run-tests.sh service_testing
    - stage: test
      script: ./run-tests.sh rest_testing
    - stage: test
      script: ./run-tests.sh galaxy_testing
    - stage: test
      script: ./run-tests.sh ui_testing
