sudo: required
language: java

services:
  - docker
  - mysql

jdk:
  - openjdk8

before_install:
  - mysql -e 'CREATE USER "test"@"localhost" IDENTIFIED BY "test"; GRANT ALL ON irida_integration_test.* to "test"@"localhost";'

install:
  - mvn -version
  - pushd lib; ./install-libs.sh; popd
  - mvn clean package -DskipTests

script: travis_wait ./run-tests.sh service_testing
