# Site settings
title: IRIDA Documentation
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
        Integrated Rapid Infectious Disease Analysis (IRIDA): A platform for genomic epidemiology.
baseurl: "/documentation" # the subpath of your site, e.g. /blog/
        # you can run the command `jekyll build --config _build-config.yml when you want to deploy
url: "https://irida.corefacility.ca/documentation" # the base hostname & protocol for your site
keep_files: [ developer/apidocs ]

# Build settings
markdown: KramdownPygments

kramdown:
        input: GFM
