# Site settings
title: IRIDA Documentation
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
        Integrated Rapid Infectious Disease Analysis (IRIDA): A platform for genomic epidemiology.
baseurl: "" # the subpath of your site, e.g. /blog/
        # you can run the command `jekyll build --baseurl "/documentation" when you want to deploy
url: "https://irida.corefacility.ca/documentation/" # the base hostname & protocol for your site

# Build settings
markdown: KramdownPygments

kramdown:
        input: GFM
